P336 Python の例外処理

chap_10_01.py を新規作成して、以下のコードを書いて実行してください

（コード以外の答えはコメントアウトで記述して下さい）

1. P339 までさらっと読んでください
1. filelen.py を新規作成して、P338の filelen.py を写経してください
1. 下記を実行してください
    ```bash
    $ python filelen.py /path/to/chap_10_01.py  
    ```
    注意：`chap_10_01.py` へのフルパスを与えてください。
1. 今度は存在しないファイルへのパスを与えて、「〜〜〜というファイルは存在しません」とプリントされるか確認してください
1. 色々例外を出していきましょうー。以下を写経して実行してください。一行ずつ書いて、エラーを確認して、エラーをコメントにメモして行きます。メモができたら、そのコードをコメントアウトして、次のコードを書いていきます。
    ```python 
    # 例
    print "Hello" 
    # SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Hello")?
    ```
    このように書いたら `print "Hello" ` をコメントアウトして次に進む、という流れです

    ```python 
    # 1
    if True:
    print("true")

    # 2 
    l = list("ABCD")
    l[1000]

    # 3 
    10 / 0 

    # 4
    smap 

    # 5 
    "100" + 3 

    # 6 
    open('hogehoge.txt')
    
    # 7 
    d = {"a": 1, "b": 2}
    d["c"]

    # 8 
    import shinseitaro
    
    # 9 
    from datetime import shinseitaro
       
    ```
1. try ~ except 文の練習をたくさんしていきましょう. 下記をコメントも含めて写経して実行して下さい。
    ```python
    import traceback
    # x = 100 
    try:
        x * 100 # x に何も代入しないまま掛け算しようとする
    except:
        traceback.print_exc()

    ```
    これで一旦実行して NameError が発生するのを確認したあと、`x = 100` のコメントをはずしてエラーがでない事を確認して下さい。
1. 同様の方法で、以下のエラーを出すコードを書いて、エラーが出ないように書き直して下さい。
    1. IndentationError
    1. IndexError
    1. TypeError
    1. FileNotFoundError
    1. KeyError
    1. ModuleNotFoundError
    1. ImportError

    