P342 例外を発生する（発生させる）

chap_10_04.py を新規作成して、以下のコードを書いて実行してください

（コード以外の答えはコメントアウトで記述して下さい）

1. raise 文は、かならず例外クラスのインスタンスとともに記述されなくてはいけません。以下のコードを順に書いて、エラーを確認して下さい
    ```python 
    # 1. 
    raise 1 

    # 2. 
    raise ValueError 

    # 3. 
    raise ValueError("何かしらの値")
    ```
    3つとも例外を返しますが、1.だけTypeErrorが返ってきたとおもいます。これは期待したを発生させたわけではなく、raise に渡すべき例外クラスを渡していないので起きるエラーです
